### show all tickets
GET http://localhost:8080/tickets
Accept: application/json

### delete ticket
DELETE http://localhost:8080/tickets/2
Authorization: Basic Shawn hello123

### add ticket
POST http://localhost:8080/tickets
Content-Type: application/json
Authorization: Basic Shawn hello123

GET 

{
    "title": "Lee Youngji",
    "ticket_number": "789",
    "seat_number": "1cxCV6",
    "unit_price": "150"
}

### update ticket
PUT http://localhost:8080/tickets/3
Content-Type: application/json
Authorization: Basic Nicholas bye123

{
    "title": "TXT Concert",
    "ticket_number": "789",
    "seat_number": "1cxCV6",
    "unit_price": "150"
}

### show all users
GET http://localhost:8080/users

### add user
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "zhirong",
    "password": "1234567898",
    "authorities": "ROLE_USER",
    "email": "jana@gmail.com",
    "address": "asdesdsaddsaads",
    "phone_num": "32165498"
}

### add user
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "Janaaaaa",
    "password": "goodpassword",
    "email": "jana@gmail.com",
    "address": "SMU building",
    "phone_num": "32165498"
}



### user buys ticket
PUT http://localhost:8080/tickets/1/3/buy
Authorization: Basic Janaaaaa goodpassword

### show specific ticket
GET http://localhost:8080/tickets/1


###
GET http://localhost:8080/users/2
Content-Type: application/json

{
    "id" : 2
}

### 
POST http://localhost:8080/transactions
Content-Type: application/json

{
    "total_price": 800,
    "user_id": 2
}

### user buys ticket
PUT http://localhost:8080/tickets/updateAvailability/4
Content-Type: application/json
Authorization: Basic Nicholas bye123

{
    "available" : true,
}

###
Post http://localhost:8080/transactions
Content-Type: application/json

{
    "total_price": 200,
    "user_id": 2

}

###
Put http://localhost:8080/tickets/updateAvailability/12
Content-Type: application/json

{
    "IsAvailable": false,
    "transaction_id": 1
}

###
Get http://localhost:8080/getTickets/2

###
Post http://localhost:8080/registration
Content-Type: application/json

{
    "username": "Janaaaaa",
    "password": "goodpassword",
    "email": "jana@gmail.com",
    "address": "SMU building",
    "phone_num": "32165498"
}



