### show all tickets
GET http://localhost:8080/tickets
Accept: application/json

### login using jwt token
POST http://localhost:8080/generateToken
Content-Type: application/json

{
    "username": "Shawn",
    "password": "hello123"
}

### delete ticket
DELETE http://localhost:8080/tickets/2
Authorization: Basic Shawn hello123

### add ticket
POST http://localhost:8080/tickets
Content-Type: application/json
Authorization: Basic Shawn hello123

{
    "title": "Lee Youngji",
    "ticket_number": "78955611",
    "seat_number": "1cxCV6afasfsa",
    "unit_price" : 500
}

### update ticket
PUT http://localhost:8080/tickets/3
Content-Type: application/json
Authorization: Basic Nicholas bye123

{
    "title": "TXT Concert",
    "ticket_number": "789",
    "seat_number": "1cxCV6",
    "unit_price": 100
}

### show all users
GET http://localhost:8080/users

### add user
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "zhirong",
    "password": "1234567898",
    "authorities": "ROLE_USER",
    "email": "zhirong@gmail.com",
    "address": "asdesdsaddsaads",
    "phone_num": "32165498"
}

### add user
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "Janaaaaa",
    "password": "goodpassword",
    "email": "jana@gmail.com",
    "address": "SMU building",
    "phone_num": "32165498"
}

### show specific ticket
GET http://localhost:8080/tickets/1

###
GET http://localhost:8080/users/2
Content-Type: application/json

{
    "id" : 2
}

### 
POST http://localhost:8080/Transactions
Content-Type: application/json

{
    "total_price": 800,
    "user_id": 3
}

### user buys ticket
PUT http://localhost:8080/tickets/updateAvailability/22
Content-Type: application/json
Authorization: Basic Janaaaaa goodpassword

{
    "available" : false
}

###
Post http://localhost:8080/Transactions
Content-Type: application/json

{
    "total_price": 200,
    "user_id": 2

}

###
Put http://localhost:8080/tickets/updateAvailability/12
Content-Type: application/json

{
    "IsAvailable": false,
    "transaction_id": 1
}

###
Get http://localhost:8080/getTickets/6

###
Post http://localhost:8080/users
Content-Type: application/json

{
    "username": "Janaaaaa",
    "password": "goodpassword",
    "email": "blessed.me.luck@gmail.com",
    "address": "SMU building",
    "phone_num": "32165498"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Janaaaaa",
    "password": "goodpassword",
    "email": "blessed.e.luck@gmail.com",
    "address": "SMU building",
    "phone_num": "32165498"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Shawn",
    "password": "hello123"
}

###
PUT http://localhost:8080/successfulTransaction/3

